name: jspaste
description: A library to interact with the JSPaste API.
version: 0.1.0
repository: https://github.com/nulkode/jspaste.dart

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
